# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ghcr.io/astral-sh/uv:python3.12-trixie-slim

ENV UV_SYSTEM_PYTHON=1
WORKDIR /app
COPY pyproject.toml ./
RUN uv pip install --no-cache -r pyproject.toml

COPY main.py ./

USER 1000
ENTRYPOINT ["python", "/app/main.py"]
